### ISSUE TITLE
CI builds ? 

### ISSUE THREAD

**Issue by shafr** [mobizt/ESP-Mail-Client#25]
Hi! 

Probably it would be a good idea to do automatic builds (something like they do here:)

https://github.com/adafruit/DHT-sensor-library/blob/master/.github/workflows/githubci.yml

This would allow you to build & test build on few platforms. (using matrix builds in CI)

Also, you can also upload action artifact, rough example:

```
  - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.test-platform }}
          path: .pio/build/${{ matrix.test-platform }}/firmware.bin  
```        

Thank you.
